name: autobuild

on:
  push:
  pull_request:
  release:
    types: published

jobs:

  build:
    name: Build ${{ matrix.config }} on ${{ matrix.os }} with ${{ matrix.arch }} arch
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        arch: [ x64, x86 ]
        config: [ debug, release ]
        exclude:
          - os: macOS-latest
            arch: x86
          - os: ubuntu-latest
            arch: x86
    steps:

    - name: Setup environment
      run: |
        pip install PyYAML

    - name: Check out gn_toolchain_sample
      uses: actions/checkout@v3
      with:
        repository: Streamlet/gn_toolchain_sample
        ref: master

    - name: Check out gn_toolchain
      uses: actions/checkout@v3
      with:
        path: build

    - name: Fetch gn and ninja
      run: |
        python build/fetch_binaries.py

    - name: Compile
      run: |
        build/bin/gn gen out/${{ matrix.config }}_${{ matrix.arch }} --args="target_cpu=\"${{ matrix.arch }}\" is_debug=${{ matrix.config == 'debug' }}"
        build/bin/ninja -C out/${{ matrix.config }}_${{ matrix.arch }}
